title: My Thoughts
description: My Blog to share my thoughts and views

url: www.melvinphilips.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: http://www.melvinphilips.com

social:
   github: melvin0008
   twitter: melvinphilips8
   email: me@melvinphilips.com

