title: Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: www.melvinphilips.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: melvin0008
   twitter: melvin0008
   email: me@melvinphilips.com

